### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by djbpitt** [HuygensING/alexandria-workshop-notebooks#1]
The double-encoding of Unicode input is gone, so show_lmnl() now returns Unicode, instead of encoded bytes. But show_text_markup() returns the following (end of trace):

/opt/conda/lib/python3.5/http/client.py in _encode(data, name)
    159             "%s (%.20r) is not valid Latin-1. Use %s.encode('utf-8') "
    160             "if you want to send it encoded in UTF-8." %
--> 161             (name.title(), data[err.start:err.end], name)) from None
    162 
    163 

UnicodeEncodeError: 'latin-1' codec can't encode character '\u2014' in position 1020: Body ('—') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

This is called from:

~/.local/lib/python3.5/site-packages/alexandria/notebook/document_proxy.py in _show_latex(self, latex)
     41 
     42     def _show_latex(self, latex):
---> 43         svg_url = self.latexutil.svg_uri(latex)
     44         display(IFrame(src=svg_url, width=950, height=300))
     45         display(HTML('<a href="' + svg_url + '" target="_new" >open in new tab</a>'))

From alexandria-workshop-notebooks/alexandria/notebook/latex_util.py:

class LaTeXUtil:
    def __init__(self, base_uri):
        self.base_uri = base_uri

    def svg_uri(self, tex):
        url = urljoin(self.base_uri, "2svg")
        session = requests.Session()
        session.headers['content-type'] = 'text/plain'
        response = session.post(url, data=tex)
        return response.headers['location']

It looks as if the header may be requesting text/plain, which might be forcing latin-1. Should we be requesting something other than plain text, perhaps the mime type of SVG?

**Comment by brambg** [comment]
fixed
